<a href="https://colab.research.google.com/github/dpkasahu/Python_library/blob/main/gfgnumpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NumPy stands for Numerical Python and is used for handling large, multi-dimensional arrays and matrices. it is faster than python lists and optimized for handling large datasets.
#numpy.array() it is for basic array creation
#numpy.arrange()


List vs numpy array

In [ ]:
py_list=[1,2,3]
print(py_list * 2)

[1, 2, 3, 1, 2, 3]


In [ ]:
import numpy as np
np_array=np.array([1,2,3]) #element wise multiplication
print(np_array * 2)

[2 4 6]


In [ ]:
import time
start = time.time()
py_list=[i*2  for i in range(10000000)]
print("list:", time.time()-start)
start=time.time()
np_array=np.array([i*2 for i in range(10000000)])
print("numpy array:",time.time()-start)

list: 0.7773799896240234
numpy array: 1.3663201332092285


Creating array from scratch

In [ ]:
zeros=np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
full = np.full((2,3),5)
full

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
random=np.random.random((2,3))
random

array([[0.63688008, 0.47537193, 0.24572483],
       [0.67783874, 0.06354924, 0.47217658]])

In [ ]:
sequence = np.arange(10,20,2)
sequence

array([10, 12, 14, 16, 18])

vector,matrix and tensor

In [ ]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [ ]:
matrix = np.array([1,2,3],[4,5,6])
matrix

In [ ]:
tensor = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Array properties

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape) #shape of array
print(arr.ndim) #dimension of an array
print(arr.dtype) #datatype of an array
print(arr.size)  #size of an array

(2, 3)
2
int64
6


Array reshaping

In [ ]:
arr=np.arange(12)
print("original array:" , arr)
arr1 = arr.reshape((3,4))
print("Reshaped array :", arr1)
arr2=arr1.flatten()
print("Flattened array :",arr2)

original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
raveled= arr1.ravel()
raveled #returns view instead of copy
#transpose
transpose = arr1.T
transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Numpy Array Operations

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,6,7,8,9])
arr[2:7]
arr[1:8:2
    ]
arr[-3]

np.int64(7)

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[1,2]
arr_2d[:,1]

array([2, 5, 8])

Sorting

In [ ]:
unsorted = np.array([3,1,2,4,5,2,7,8,2])
np.sort(unsorted)
arr_2d_unsorted = np.array([[3,1] , [1,2] , [2,3]])
np.sort(arr_2d_unsorted,axis=0)

array([[1, 1],
       [2, 2],
       [3, 3]])

Filter

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = numbers[numbers % 2 ==0]
even_num

array([ 2,  4,  6,  8, 10])

Filter with mask

In [ ]:
mask = numbers > 5
numbers[mask]

array([ 6,  7,  8,  9, 10])

Fancy indexing vs np.where()

In [ ]:
indices = [0,2,4]
numbers[indices]
where_res = np.where(numbers>5)
print(where_res)
print(numbers[where_res])

(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [6]:
import numpy as np
cond_array = np.where(numbers > 5,"true", "false")
print(cond_array)
# print(numbers[cond_array])


['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


Adding and removing data

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
# combined
# arr1 + arr2

array([5, 7, 9])

Array compatibility

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,8,6])
c= np.array([7,8,9])
a.shape==b.shape
a.shape == c.shape

True

Vstack and Hstack

In [14]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)
arr=np.array([[7],[8]])
with_new_col = np.hstack((original,arr))
print(with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]
