<a href="https://colab.research.google.com/github/dpkasahu/numpy/blob/main/numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#pip install numpy   ------> installation of numpy, it is already installed no need to install
import numpy as np

#importing numpy and giving name np as alias name
#numpy is an numerical python which deals with array
#consist of homogenous values and stores in a sequential format
#array is faster as compared to list
#it is used to create multidimensional array

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a=[1,2,3,4,{1,2,3}]
arr = np.array(a)
arr

array([1, 2, 3, 4, {1, 2, 3}], dtype=object)

In [ ]:
a = [[[1,2,3],[4,6,6]]]
arr = np.array(a)
arr.ndim #ndim is a variable , it is used to check the dimension of an array

3

In [ ]:
arr = [1,2,3,4,5,4.3]
arr = np.array(a)
#type(arr) #numpy.ndarray
type(arr[0]) #numpy.int64

numpy.ndarray

Shape of array


In [ ]:
import numpy as np
a=[1,2,3,4,5,6]
arr = np.array(a)
arr.shape

(6,)

In [ ]:
a = [[[1,2,3],[4,6,6]]]
arr = np.array(a)
arr.shape

(1, 2, 3)

In [ ]:
#reshape                                                              #date=09/11/2025
#it is an inbuilt function used to reshape the array or to change the shape.
#it will change the dimension also
#product of row and column should be number of elements
import numpy as np
a=[1,2,3,4,5,6]
arr = np.array(a)
arr2=arr.reshape(6,1)
print(arr2)
arr2.ndim

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


2

In [ ]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,6,8]]
arr=np.array(a)
arr2=arr.reshape(1,9,1) #for 3d we have to give row,column and depth
arr3=arr.reshape(9,1)
arr2
# arr3

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [6],
        [8]]])

In [ ]:
a=[[1,2,3],[4,5,6],[7,6,8]]
arr=np.array(a)
# arrr=arr.reshape(9,)
arrr=arr.reshape(-1) #flattening of array and convert into 1-d array
arrr

array([1, 2, 3, 4, 5, 6, 7, 6, 8])

In [ ]:
list(range(1,11,1))
#arrange
# inbuilt function to create sequence of values
# syntax:= np.arange(s.v,e.v,up)
np.arange(1,21,1)
#we dont need to type caste in arange but in range we have to type caste .

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
lst = []
def prime():
  for i in range(2,100):
    for j in range(2,int(i**0.5)+1):
      if i % j == 0:
        break
    else:
        lst.append(i)
prime()
# print(lst)
arr=np.array(lst)
# type(arr)
arr2=arr.reshape(len(lst),1)
arr2.ndim
# arr2

2

In [ ]:
#random module
# np.random.randint(s.v , e.v,n) n is number of values required
np.random.randint(1,10,3)
#n is optional by default it will give one value
#generate 20 random values between 1 to 100
np.random.randint(1,10,22)

array([9, 2, 3, 8, 5, 4, 1, 9, 5, 8, 6, 3, 9, 6, 4, 9, 7, 3, 6, 3, 6, 8])

In [ ]:
# np.random.rand(n)
np.random.rand(2)
#n is optional it will give one value by default
#randn will give any kind of values which includes float value
np.random.randn(2)

array([1.00944773, 0.27355649])

create a 2d numpy array of shape (3,3), filled with random integer between 1 and 10.

In [ ]:
import numpy as np
import random
data=[]
for i in range(3):
  row=[]
  for j in range(3):
    row.append(random.randint(1,10))
  data.append(row)
arr=np.array(data)
arr
#another method
arr=np.random.randint(1,11,(3,3))
arr



array([[5, 5, 9],
       [2, 4, 4],
       [4, 3, 7]])

How do you find the shape , dimension and datatype of a numpy array.

In [ ]:
import numpy as np
a=[1,2,3,4,5]
arr=np.array(a)
arr.shape
arr.ndim
type(arr)

numpy.ndarray

Generate an array of even numbers between 2 to 20.

In [ ]:
import numpy as np
arr=[]
for i in range(2,21,2):
  arr.append(i)

arr1=np.array(arr)
arr1
#another method
arr=np.arange(2,21,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Create an one 1-d array of 9 elements and reshape into (3,3).


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = arr.reshape(3, 3)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


what is flattening of array.

In [ ]:
#Flattening means converting a multi-dimensional array (like 2D or 3D) into a 1D array.


In [ ]:
np.random.randn(6)
#it is an inbuilt function inside random module which generate random float between -infinity to infinity.

array([ 0.92955598,  0.12302778,  0.79855393, -0.15569701,  1.20861687,
        0.87008998])

In [ ]:
#np.linspace(s.v,e.v,n) n---> n is number of partition
#it is an inbuilt function which divides the given range from s.v to e.v in to n equal parts
np.linspace(1,10,10)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# np.zeros(n) n---> it is number of values or shape, it is an inbuilt function which will generate the n number of zeros with resepctive to shape
np.zeros((3,3)) #for 2d we have to give row and columns


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# np.ones(2) #it is an inbuilt function which will generate the n number of ones with resepctive to shape
np.ones((3,3)) #for 2d array we have to give shape

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.identity(2)
#it s an inbuilt function used to create identity matrix where diagonal elements will be one.

array([[1., 0.],
       [0., 1.]])

COPY OPERATION

In [ ]:
#normal copy = if u change the destination variable it will change the source variable
#dest_variable = src_variable (syntax)
#in this copy operation when src_variable memory address will get copied to dest_variable
a=np.array([1,2,3,4,5])
b=a
a[2]=30
b

array([ 1,  2, 30,  4,  5])

In [ ]:
#shallow copy = if you change the destination variable it will not change the source variable
#it is an copy operation when the value space will get copied to dest_variable
#dest_var = src_var.copy()
dest_var = src_var.copy()
b = np.array([1,2,3,4,5])
c=b.copy()
c[2]=20
b

array([1, 2, 3, 4, 5])

DIFFERENCE BETWEEN VIEW() AND NORMAL COPY.

In [ ]:
#IN NORMAL COPY SRC_VAR AND DEST_VAR WILL HAVE SAME ADDRESS.
#IN view() src_var and dest_var will have different address.

In [ ]:
#view()
d=np.array([1,2,3,4,5])
e=d.view()
e[2]=30
d

array([ 1,  2, 30,  4,  5])

indexing

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
# arr[2]
arr[-1]

np.int64(5)

In [5]:
arr2=[[1,2,3],[4,5,6],[7,8,9]]
arr2[1][2]


6