<a href="https://colab.research.google.com/github/dpkasahu/numpy/blob/main/numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#pip install numpy   ------> installation of numpy, it is already installed no need to install
import numpy as np

#importing numpy and giving name np as alias name
#numpy is an numerical python which deals with array
#consist of homogenous values and stores in a sequential format
#array is faster as compared to list
#it is used to create multidimensional array

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a=[1,2,3,4,{1,2,3}]
arr = np.array(a)
arr

array([1, 2, 3, 4, {1, 2, 3}], dtype=object)

In [ ]:
a = [[[1,2,3],[4,6,6]]]
arr = np.array(a)
arr.ndim #ndim is a variable , it is used to check the dimension of an array

3

In [ ]:
arr = [1,2,3,4,5,4.3]
arr = np.array(a)
#type(arr) #numpy.ndarray
type(arr[0]) #numpy.int64

numpy.ndarray

In [ ]:
#reshape                                                              #date=09/11/2025
#it is an inbuilt function used to reshape the array or to change the shape.
#it will change the dimension also
#product of row and column should be number of elements
import numpy as np
a=[1,2,3,4,5,6]
arr = np.array(a)
arr2=arr.reshape(6,1)
print(arr2)
arr2.ndim

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


2

In [ ]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,6,8]]
arr=np.array(a)
arr2=arr.reshape(1,9,1) #for 3d we have to give row,column and depth
arr3=arr.reshape(9,1)
arr2
# arr3

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [6],
        [8]]])

In [ ]:
a=[[1,2,3],[4,5,6],[7,6,8]]
arr=np.array(a)
# arrr=arr.reshape(9,)
arrr=arr.reshape(-1) #flattening of array and convert into 1-d array
arrr

array([1, 2, 3, 4, 5, 6, 7, 6, 8])

In [ ]:
list(range(1,11,1))
#arrange
# inbuilt function to create sequence of values
# syntax:= np.arange(s.v,e.v,up)
np.arange(1,21,1)
#we dont need to type caste in arange but in range we have to type caste .

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
lst = []
def prime():
  for i in range(2,100):
    for j in range(2,int(i**0.5)+1):
      if i % j == 0:
        break
    else:
        lst.append(i)
prime()
# print(lst)
arr=np.array(lst)
# type(arr)
arr2=arr.reshape(len(lst),1)
arr2.ndim
# arr2

2

In [ ]:
#random module
# np.random.randint(s.v , e.v,n) n is number of values required
np.random.randint(1,10,3)
#n is optional by default it will give one value
#generate 20 random values between 1 to 100
np.random.randint(1,10,22)

array([9, 2, 3, 8, 5, 4, 1, 9, 5, 8, 6, 3, 9, 6, 4, 9, 7, 3, 6, 3, 6, 8])

In [ ]:
# np.random.rand(n)
np.random.rand(2)
#n is optional it will give one value by default
#randn will give any kind of values which includes float value
np.random.randn(2)

array([1.00944773, 0.27355649])