<a href="https://colab.research.google.com/github/dpkasahu/numpy/blob/main/practice01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 1D NumPy array of 10 elements from 10 to 100 (step 10) and print 3rd and last element

In [1]:
import numpy as np
arr=np.arange(10,101,10)
arr[2]
arr[-1]


np.int64(100)

2.Given arr = np.array([5, 10, 15, 20, 25, 30, 35]): Extract elements from index 2 to 5 and reverse
the array using slicing.


In [5]:
arr = np.array([5, 10, 15, 20, 25, 30, 35])
arr[2:6]
arr[::-1]

array([35, 30, 25, 20, 15, 10,  5])

3. Create a 2D array [[10,20,30],[40,50,60],[70,80,90]]. Access the element 60 using indexing.

In [6]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr[1][2]

np.int64(60)

4. Using the same array, print the first row and second column using slicing

In [13]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
# arr[:1]
arr[::,1:2]

array([[20],
       [50],
       [80]])

5. Extract the first two rows and last two columns from [[1,2,3,4],[5,6,7,8],[9,10,11,12]].

In [16]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[:2,2:]

array([[3, 4],
       [7, 8]])

6. Create a 1D array of numbers 1 to 15 and extract every second element and every third element
starting from index 1

In [19]:
arr=np.arange(1,16)
print("Every 2nd element:",arr[::2])
print("Every 3rd element from index 1:", arr[1::3])

Every 2nd element: [ 1  3  5  7  9 11 13 15]
Every 3rd element from index 1: [ 2  5  8 11 14]


7. Given arr = np.arange(1, 10).reshape(3, 3): Extract the second row and first column.

In [28]:
arr = np.arange(1, 10).reshape(3, 3)
# arr[1:2:]
arr[::,:1]


array([[1],
       [4],
       [7]])