<a href="https://colab.research.google.com/github/dpkasahu/numpy/blob/main/practice01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 1D NumPy array of 10 elements from 10 to 100 (step 10) and print 3rd and last element

In [1]:
import numpy as np
arr=np.arange(10,101,10)
arr[2]
arr[-1]


np.int64(100)

2.Given arr = np.array([5, 10, 15, 20, 25, 30, 35]): Extract elements from index 2 to 5 and reverse
the array using slicing.


In [5]:
arr = np.array([5, 10, 15, 20, 25, 30, 35])
arr[2:6]
arr[::-1]

array([35, 30, 25, 20, 15, 10,  5])

3. Create a 2D array [[10,20,30],[40,50,60],[70,80,90]]. Access the element 60 using indexing.

In [6]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr[1][2]

np.int64(60)

4. Using the same array, print the first row and second column using slicing

In [13]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
# arr[:1]
arr[::,1:2]

array([[20],
       [50],
       [80]])

5. Extract the first two rows and last two columns from [[1,2,3,4],[5,6,7,8],[9,10,11,12]].

In [16]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[:2,2:]

array([[3, 4],
       [7, 8]])

6. Create a 1D array of numbers 1 to 15 and extract every second element and every third element
starting from index 1

In [19]:
arr=np.arange(1,16)
print("Every 2nd element:",arr[::2])
print("Every 3rd element from index 1:", arr[1::3])

Every 2nd element: [ 1  3  5  7  9 11 13 15]
Every 3rd element from index 1: [ 2  5  8 11 14]


7. Given arr = np.arange(1, 10).reshape(3, 3): Extract the second row and first column.

In [28]:
arr = np.arange(1, 10).reshape(3, 3)
# arr[1:2:]
arr[::,:1]


array([[1],
       [4],
       [7]])

8. For arr = np.arange(1, 13).reshape(3, 4): Use slicing to get [[2, 3], [6, 7]].

In [30]:
arr = np.arange(1, 13).reshape(3, 4)
arr[:2:,1:3]

array([[2, 3],
       [6, 7]])

9. Create an array from 1 to 20 and print the last 5 elements using slicing.

In [33]:
arr = np.arange(1, 21)
arr[-5:]

array([16, 17, 18, 19, 20])

10. Using a 4x3 array [[1,2,3],[4,5,6],[7,8,9],[10,11,12]], extract the 2nd and 4th rows only.

In [34]:
arr=np.array( [[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr[1::2]

array([[ 4,  5,  6],
       [10, 11, 12]])

11. From the same array, extract all rows but only the 1st and 3rd columns.

In [35]:
arr=np.array( [[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr[::,0:2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

12. Create a 4x4 array with numbers 1 to 16 and extract the corner elements using indexing.

In [36]:
arr = np.arange(1, 17).reshape(4, 4)
arr[[0, -1]][:, [0, -1]]

array([[ 1,  4],
       [13, 16]])

13. Given arr = np.array([10, 20, 30, 40, 50, 60]): Extract [30, 40, 50], [10, 20, 30, 40], and reverse
the array.

In [37]:
arr = np.array([10,20,30,40,50,60])
print(arr[2:5])
print(arr[:4])
print(arr[::-1])


[30 40 50]
[10 20 30 40]
[60 50 40 30 20 10]


14. Using boolean indexing, from arr = np.array([3, 7, 12, 18, 25, 30]), select all elements greater
than 10.

In [38]:
arr=np.array([3,7,17,33,25])
arr[arr>10]

array([17, 33, 25])

15. Create a 3x3 NumPy array and replace all elements in the second column with 0 using slicing and assignment.

In [40]:
arr = np.arange(1, 10).reshape(3, 3)
arr[:,1]=0
arr

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

16. Given arr = [[11,12,13,14],[21,22,23,24],[31,32,33,34],[41,42,43,44]]: Extract rows 1 and 3, and
columns 2 and 4.

17. Using fancy indexing, extract elements at positions (0,0), (1,1), (2,2), (3,3) from a 4x4 array
(main diagonal).

18. Create a 4x5 array with numbers from 10 to 29 and use slicing to extract a subarray of shape (2,
3) from the middle.

19. Given arr = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]: Use slicing to get [[6,7],[10,11]].


In [ ]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr[1:, 1:3])


20. Create a 2D array of marks for 5 students and 4 subjects (random integers between 40 and
100). Use indexing to print marks of the 3rd student and slicing to print marks of all students in the
first two subjects.